# Generated by Django 3.1.4 on 2021-01-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('oid', models.TextField(primary_key=True, serialize=False)),
                ('pid', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('profile_image', models.ImageField(default='user-regular.svg', upload_to='')),
                ('desgn', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('password', models.TextField(default='')),
            ],
        ),
    ]
