# Generated by Django 3.1.4 on 2021-01-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='desgn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pid',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='img_obj',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
