# Generated by Django 3.1.4 on 2021-01-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_auto_20210104_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='oid',
            new_name='uid',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default=''),
        ),
    ]
