# Generated by Django 3.1.4 on 2021-05-16 04:51

from django.db import migrations, models
import user_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_auto_20210516_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='user-regular.png', upload_to=user_auth.models.set_image_path_user),
        ),
    ]
