# Generated by Django 3.1.4 on 2021-01-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('nid', models.IntegerField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('type', models.TextField()),
                ('title', models.TextField()),
                ('station_id', models.TextField(blank=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Offence',
            fields=[
                ('Offence_id', models.IntegerField(primary_key=True, serialize=False)),
                ('registration_date', models.DateField()),
                ('applicant_name', models.TextField()),
                ('applicant_gender', models.TextField()),
                ('applicant_contact_number', models.IntegerField(max_length=10)),
                ('applicant_id', models.IntegerField(null=True)),
                ('applicant_address', models.TextField()),
                ('date_time_offence', models.DateTimeField()),
                ('nature_offence', models.TextField()),
                ('offence_description', models.TextField()),
                ('accused_id', models.IntegerField(null=True)),
                ('accused_name', models.TextField()),
                ('accused_gender', models.TextField()),
                ('accused_contact_number', models.IntegerField(max_length=10)),
                ('accused_address', models.TextField()),
            ],
        ),
    ]
