# Generated by Django 3.1.4 on 2021-01-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0002_auto_20210124_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offence',
            old_name='Offence_id',
            new_name='offence_id',
        ),
    ]
