# Generated by Django 3.1.4 on 2021-01-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0003_auto_20210124_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offender',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('dob', models.DateField()),
                ('gender', models.TextField()),
                ('contact_number', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='offence',
            name='accused_address',
        ),
        migrations.RemoveField(
            model_name='offence',
            name='accused_contact_number',
        ),
        migrations.RemoveField(
            model_name='offence',
            name='accused_gender',
        ),
        migrations.RemoveField(
            model_name='offence',
            name='accused_name',
        ),
        migrations.RemoveField(
            model_name='offence',
            name='applicant_gender',
        ),
    ]
