# Generated by Django 3.1.4 on 2021-01-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0004_auto_20210127_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('sid', models.TextField(primary_key=True, serialize=False)),
                ('branch_name', models.TextField(max_length=24, unique=True)),
                ('address', models.TextField()),
                ('state', models.TextField(default='')),
                ('district', models.TextField(default='')),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='offender',
            name='gender',
        ),
        migrations.AddField(
            model_name='offence',
            name='applicant_image',
            field=models.ImageField(default='user-regular.svg', upload_to=''),
        ),
        migrations.AddField(
            model_name='offence',
            name='img_obj',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offender',
            name='img_obj',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offender',
            name='profile_image',
            field=models.ImageField(default='user-regular.svg', upload_to=''),
        ),
    ]
