# Generated by Django 3.1.4 on 2021-01-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0005_auto_20210127_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='offence',
            name='gender',
            field=models.TextField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('TRANSGENDER', 'Transgender'), ('OTHER', 'Other')], default='OTHER'),
        ),
        migrations.AddField(
            model_name='offender',
            name='gender',
            field=models.TextField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('TRANSGENDER', 'Transgender'), ('OTHER', 'Other')], default='OTHER'),
        ),
    ]
