# Generated by Django 3.1.4 on 2021-02-03 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0006_auto_20210128_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 3, 16, 0, 19, 594456, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.IntegerField(default='5A3C28', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='486192B8', primary_key=True, serialize=False),
        ),
    ]
