# Generated by Django 3.1.4 on 2021-02-04 15:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0007_auto_20210203_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 4, 15, 39, 32, 700950, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='D3EA37', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='43191C95', primary_key=True, serialize=False),
        ),
    ]
