# Generated by Django 3.1.4 on 2021-02-09 16:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0008_auto_20210204_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offence',
            name='applicant_image',
        ),
        migrations.RemoveField(
            model_name='offence',
            name='img_obj',
        ),
        migrations.RemoveField(
            model_name='offence',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='offence',
            name='registration_date_time',
            field=models.DateField(default=datetime.datetime(2021, 2, 9, 16, 1, 2, 664826, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='offence',
            name='station_id',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='notice',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 9, 16, 1, 2, 667409, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='387882', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='offence_id',
            field=models.TextField(default='779DF7DE', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='4ACB0917', primary_key=True, serialize=False),
        ),
    ]
