# Generated by Django 3.1.4 on 2021-02-10 06:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0009_auto_20210209_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='offender',
            name='offender_uid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 10, 6, 26, 1, 987256, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='54C526', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='offence_id',
            field=models.TextField(default='128CD5A2', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='registration_date_time',
            field=models.DateField(default=datetime.datetime(2021, 2, 10, 6, 26, 1, 984926, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offender',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='offender',
            name='contact_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='offender',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='offender',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='img_obj',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='B1E5938C', primary_key=True, serialize=False),
        ),
    ]
