# Generated by Django 3.1.4 on 2021-02-10 07:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0010_auto_20210210_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 10, 7, 11, 48, 831142, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='C67B93', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='offence_id',
            field=models.TextField(default='A1BF0361', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='registration_date_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='offender',
            name='id',
            field=models.TextField(default='A6770F', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='199E033E', primary_key=True, serialize=False),
        ),
    ]
