# Generated by Django 3.1.4 on 2021-02-11 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0011_auto_20210210_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='338001', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='applicant_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='offence',
            name='offence_id',
            field=models.TextField(default='D6EA51A3', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='id',
            field=models.TextField(default='0B6CA9', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='offender_uid',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='4CB6EC6C', primary_key=True, serialize=False),
        ),
    ]
