# Generated by Django 3.1.4 on 2021-02-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0012_auto_20210211_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offence',
            old_name='applicant_address',
            new_name='place_offence',
        ),
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='2477E0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='accused_id',
            field=models.IntegerField(default='7D74EA', null=True),
        ),
        migrations.AlterField(
            model_name='offence',
            name='offence_id',
            field=models.TextField(default='469591A5', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='id',
            field=models.TextField(default='9EB51A', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='D42EB59F', primary_key=True, serialize=False),
        ),
    ]
