# Generated by Django 3.1.4 on 2021-02-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0013_auto_20210211_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offender',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='offender',
            name='dob',
        ),
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='DD6A3A', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='accused_id',
            field=models.IntegerField(default='B33C28', null=True),
        ),
        migrations.AlterField(
            model_name='offence',
            name='offence_id',
            field=models.TextField(default='DD3E5DA3', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='id',
            field=models.TextField(default='5C7928', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='6761CE44', primary_key=True, serialize=False),
        ),
    ]
