# Generated by Django 3.1.4 on 2021-02-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0014_auto_20210213_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='147313', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='accused_id',
            field=models.TextField(default='6665CF', null=True),
        ),
        migrations.AlterField(
            model_name='offence',
            name='offence_id',
            field=models.TextField(default='57B29386', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='id',
            field=models.TextField(default='893AA6', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='F1204C60', primary_key=True, serialize=False),
        ),
    ]
