# Generated by Django 3.1.4 on 2021-02-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0015_auto_20210213_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='436374', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='accused_id',
            field=models.TextField(blank=True, default='B8185F', null=True),
        ),
        migrations.AlterField(
            model_name='offence',
            name='offence_id',
            field=models.TextField(default='AE6F1BE9', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='id',
            field=models.TextField(default='3CC3A2', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='37936E22', primary_key=True, serialize=False),
        ),
    ]
