# Generated by Django 3.1.4 on 2021-02-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0018_auto_20210217_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='88F7DC', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='applicant_contact_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='offence',
            name='applicant_uid',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='offence',
            name='offence_id',
            field=models.TextField(default='3BA993', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='contact_number',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='offender',
            name='id',
            field=models.TextField(default='9A2C45', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='uid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='71573DF6', primary_key=True, serialize=False),
        ),
    ]
