# Generated by Django 3.1.4 on 2021-02-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0019_auto_20210218_0536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offence',
            old_name='place_offence',
            new_name='offence_place',
        ),
        migrations.RenameField(
            model_name='offence',
            old_name='offence_reg_date_time',
            new_name='offence_reg_timestamp',
        ),
        migrations.RenameField(
            model_name='offender',
            old_name='portrait_img',
            new_name='face_img',
        ),
        migrations.RemoveField(
            model_name='offence',
            name='nature_offence',
        ),
        migrations.RemoveField(
            model_name='offence',
            name='offence_id',
        ),
        migrations.RemoveField(
            model_name='offence',
            name='suspect_id',
        ),
        migrations.RemoveField(
            model_name='offender',
            name='face_id_obj',
        ),
        migrations.AddField(
            model_name='offence',
            name='accused_id',
            field=models.TextField(blank=True, default='Unkown', null=True),
        ),
        migrations.AddField(
            model_name='offence',
            name='id',
            field=models.TextField(default='E', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='offence',
            name='offence_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='offence',
            name='station_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='offender',
            name='face_obj',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='0B4A70', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='applicant_contact_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='offence',
            name='applicant_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='offence',
            name='status',
            field=models.TextField(choices=[('OPEN', 'open'), ('CLOSE', 'Close')], default='OPEN'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='contact_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='offender',
            name='id',
            field=models.TextField(default='7', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='uid',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='4C60A5CE', primary_key=True, serialize=False),
        ),
    ]
