# Generated by Django 3.1.4 on 2021-02-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0020_auto_20210228_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='213FD7', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='id',
            field=models.TextField(default='3', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='contact_number',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='offender',
            name='id',
            field=models.TextField(default='2', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='390A3766', primary_key=True, serialize=False),
        ),
    ]
