# Generated by Django 3.1.4 on 2021-03-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0021_auto_20210228_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='860A3E', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='id',
            field=models.TextField(default='8', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='face_img',
            field=models.ImageField(default='user-regular.svg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='id',
            field=models.TextField(default='1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='C9EEFD2F', primary_key=True, serialize=False),
        ),
    ]
