# Generated by Django 3.1.4 on 2021-03-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0022_auto_20210303_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='04EB85', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='id',
            field=models.TextField(default='A', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='face_img',
            field=models.ImageField(default='user-regular.svg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='id',
            field=models.TextField(default='B', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='4A80B887', primary_key=True, serialize=False),
        ),
    ]
