# Generated by Django 3.1.4 on 2021-03-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0023_auto_20210303_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='0BD66F', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='id',
            field=models.TextField(default='2', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='face_img',
            field=models.ImageField(default='user-regular.svg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='offender',
            name='id',
            field=models.TextField(default='9', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='E6E700B3', primary_key=True, serialize=False),
        ),
    ]
