# Generated by Django 3.1.4 on 2021-03-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0024_auto_20210303_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='33A0AD', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='id',
            field=models.TextField(default='B8F2E5', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='offender',
            name='id',
            field=models.TextField(default='D0D277', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='uid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='1969F333', primary_key=True, serialize=False),
        ),
    ]
