# Generated by Django 3.1.4 on 2021-04-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0029_auto_20210403_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='052CA7', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='id',
            field=models.TextField(default='95F2F1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='id',
            field=models.TextField(default='32B012', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='497797F1', primary_key=True, serialize=False),
        ),
    ]
