# Generated by Django 3.1.4 on 2021-04-15 13:39

from official_app.models import Offence
from django.db import migrations, models
from django.db.migrations.operations.fields import AlterField
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0031_auto_20210410_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offence',
            name='station_id',
        ),
        migrations.AddField(
            model_name='offence',
            name='station',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='official_app.station'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='C8A999', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='id',
            field=models.TextField(default='2168E7', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='id',
            field=models.TextField(default='08419B', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='91936A82', primary_key=True, serialize=False),
        ),
    ]
