# Generated by Django 3.1.4 on 2021-04-15 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0034_auto_20210415_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='station_id',
        ),
        migrations.AddField(
            model_name='notice',
            name='station',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='official_app.station'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='C3CE2D', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='id',
            field=models.TextField(default='DCAC73', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='id',
            field=models.TextField(default='5EE11C', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='61C992FB', primary_key=True, serialize=False),
        ),
    ]
