# Generated by Django 3.1.4 on 2021-04-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0036_auto_20210415_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='D56A74', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='id',
            field=models.TextField(default='C920E1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='id',
            field=models.TextField(default='8BC3B7', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='4DCDF87B', primary_key=True, serialize=False),
        ),
    ]
