# Generated by Django 3.1.4 on 2021-04-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0043_auto_20210415_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='7A1A67', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='id',
            field=models.TextField(default='56A859', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='id',
            field=models.TextField(default='C78E06', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='3CBC5FE0', primary_key=True, serialize=False),
        ),
    ]
