# Generated by Django 3.1.4 on 2021-04-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0044_auto_20210422_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='FDF8BD', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='id',
            field=models.TextField(default='B619E9', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='id',
            field=models.TextField(default='0C7EB3', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='D1E52363', primary_key=True, serialize=False),
        ),
    ]
