# Generated by Django 3.1.4 on 2021-05-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0045_auto_20210422_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offence',
            name='accused_id',
        ),
        migrations.AddField(
            model_name='offence',
            name='offenders',
            field=models.ManyToManyField(to='official_app.Offender'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='56CB2B', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='id',
            field=models.TextField(default='583B68', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='id',
            field=models.TextField(default='D63731', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='FAC6CB0E', primary_key=True, serialize=False),
        ),
    ]
