# Generated by Django 3.1.4 on 2021-05-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0047_auto_20210508_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='7EBFCC', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='applicant_contact_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='offence',
            name='id',
            field=models.TextField(default='26D7A2', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='id',
            field=models.TextField(default='A5F524', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='71AF28A7', primary_key=True, serialize=False),
        ),
    ]
