# Generated by Django 3.1.4 on 2021-05-12 11:11

from django.db import migrations, models
import official_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0048_auto_20210509_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='01BBE1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='id',
            field=models.TextField(default='F75000', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='face_img',
            field=models.ImageField(default='user-regular.png', upload_to=official_app.models.set_image_path_offender),
        ),
        migrations.AlterField(
            model_name='offender',
            name='id',
            field=models.TextField(default='279A55', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='51375932', primary_key=True, serialize=False),
        ),
    ]
