# Generated by Django 3.1.4 on 2021-05-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0050_auto_20210513_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='C207CC', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='applicant_gender',
            field=models.TextField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('other', 'Other')], default='OTHER'),
        ),
        migrations.AlterField(
            model_name='offence',
            name='id',
            field=models.TextField(default='D79BCE', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='status',
            field=models.TextField(choices=[('open', 'open'), ('close', 'close')], default='open'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='gender',
            field=models.TextField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('other', 'Other')], default='OTHER'),
        ),
        migrations.AlterField(
            model_name='offender',
            name='id',
            field=models.TextField(default='CFB13D', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='48A7EBB6', primary_key=True, serialize=False),
        ),
    ]
