# Generated by Django 3.1.4 on 2021-05-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0055_auto_20210515_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='02A4B1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='id',
            field=models.TextField(default='B4CBB6', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='id',
            field=models.TextField(default='6E6575', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='909AACF5', primary_key=True, serialize=False),
        ),
    ]
