# Generated by Django 3.1.4 on 2021-05-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0056_auto_20210516_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.TextField(default='AA5678', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='id',
            field=models.TextField(default='312000', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='id',
            field=models.TextField(default='838DD1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='sid',
            field=models.TextField(default='5D1820F3', primary_key=True, serialize=False),
        ),
    ]
