# Generated by Django 3.1.4 on 2020-12-28 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('sid', models.TextField(primary_key=True, serialize=False)),
                ('branch_name', models.TextField(max_length=24, unique=True)),
                ('n_officials', models.IntegerField(blank=True, default=0)),
                ('n_offenders', models.IntegerField(blank=True, default=0)),
                ('n_requests', models.IntegerField(blank=True, default=0)),
                ('n_notices', models.IntegerField(blank=True, default=0)),
                ('address', models.TextField()),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Official',
            fields=[
                ('oid', models.TextField(primary_key=True, serialize=False)),
                ('pid', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('n_firs', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('n_requests', models.IntegerField(default=0)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='official_auth.station')),
            ],
        ),
    ]
