# Generated by Django 3.1.4 on 2020-12-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='district',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='station',
            name='state',
            field=models.TextField(default=''),
        ),
    ]
