# Generated by Django 3.1.4 on 2020-12-29 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('official_auth', '0003_official_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='sid',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='official_auth.station'),
        ),
    ]
