# Generated by Django 3.1.4 on 2020-12-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_auth', '0005_auto_20201229_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='official',
            name='n_firs',
        ),
        migrations.RemoveField(
            model_name='official',
            name='n_requests',
        ),
        migrations.RemoveField(
            model_name='station',
            name='n_notices',
        ),
        migrations.RemoveField(
            model_name='station',
            name='n_offenders',
        ),
        migrations.RemoveField(
            model_name='station',
            name='n_officials',
        ),
        migrations.RemoveField(
            model_name='station',
            name='n_requests',
        ),
        migrations.AddField(
            model_name='official',
            name='desgn',
            field=models.TextField(default=''),
        ),
    ]
