# Generated by Django 3.1.4 on 2021-01-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_auth', '0007_auto_20201229_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='official',
            name='profile_image',
            field=models.ImageField(default='/static/images/user-regular.svg', upload_to='static/images/{oid}/'),
        ),
    ]
