# Generated by Django 3.1.4 on 2021-01-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_auth', '0008_official_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='profile_image',
            field=models.ImageField(default='/static/images/user-regular.svg', upload_to='static/images'),
        ),
    ]
