# Generated by Django 3.1.4 on 2021-01-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_auth', '0011_auto_20210104_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='profile_image',
            field=models.ImageField(default='user-regular.svg', upload_to=models.TextField(primary_key=True, serialize=False)),
        ),
    ]
