# Generated by Django 3.1.4 on 2021-01-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_auth', '0012_auto_20210104_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='profile_image',
            field=models.ImageField(default='user-regular.svg', upload_to=''),
        ),
    ]
