# Generated by Django 3.1.4 on 2021-01-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_auth', '0013_auto_20210104_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='official',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='official',
            name='district',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='official',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='official',
            name='state',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
