# Generated by Django 3.1.4 on 2021-01-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_auth', '0014_auto_20210104_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='district',
            field=models.TextField(blank=True, default='', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='official',
            name='state',
            field=models.TextField(blank=True, default='', max_length=24, null=True),
        ),
    ]
