# Generated by Django 3.1.4 on 2021-01-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_auth', '0016_auto_20210104_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='official',
            name='img_obj',
            field=models.TextField(blank=True),
        ),
    ]
