# Generated by Django 3.1.4 on 2021-01-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_auth', '0017_official_img_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='official',
            name='gender',
            field=models.TextField(default=''),
        ),
    ]
