# Generated by Django 3.1.4 on 2021-01-27 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0005_auto_20210127_1619'),
        ('official_auth', '0019_remove_official_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='official_app.station'),
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
