# Generated by Django 3.1.4 on 2021-04-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('official_auth', '0022_auto_20210321_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='official',
            name='verified',
        ),
    ]
