# Generated by Django 3.1.4 on 2021-04-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_auth', '0023_remove_official_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='desgn',
            field=models.TextField(choices=[('Director General of Police (DGP)', 'Director General of Police (DGP)'), ('Additional Director General Of Police (ADGP)', ' Additional Director General Of Police (ADGP)'), ('Inspector General Of Police/ Special Inspector General Of Police (IGP/SIGP)', 'Inspector General Of Police/ Special Inspector General Of Police (IGP/SIGP)'), ('Deputy Inspector General Of Police (DIGP)', 'Deputy Inspector General Of Police (DIGP)'), ('Superintendent of Police/Deputy Commissioner Of Police (SP/DCP)', 'Superintendent of Police/Deputy Commissioner Of Police (SP/DCP)'), ('Superintendent of Police/Deputy Commissioner Of Police (Junior Management Level)', 'Superintendent of Police/Deputy Commissioner Of Police (Junior Management Level)'), ('Additional Superintendent Of Police/Deputy Commissioner of Police (ASP/DCP)', 'Additional Superintendent Of Police/Deputy Commissioner of Police (ASP/DCP)'), ('Police Inspector (P.I.)', 'Police Inspector (P.I.)'), (' Assistant Police Inspector (A.P.I.)', ' Assistant Police Inspector (A.P.I.)'), ('Police Sub-Inspector (SI)', 'Police Sub-Inspector (SI)'), ('Assistant Police Sub-Inspector (ASI)', 'Assistant Police Sub-Inspector (ASI)'), ('Head Constable (HC)', 'Head Constable (HC)'), ('Police Constable (PC)', 'Police Constable (PC)')]),
        ),
    ]
