# Generated by Django 3.1.4 on 2021-04-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_auth', '0025_auto_20210409_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='district',
            field=models.TextField(blank=True, choices=[], default='', null=True),
        ),
    ]
