# Generated by Django 3.1.4 on 2021-05-15 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('official_app', '0051_auto_20210515_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('applicant_name', models.TextField()),
                ('applicant_uid', models.TextField()),
                ('applicant_gender', models.TextField()),
                ('applicant_address', models.TextField(null=True)),
                ('request', models.TextField()),
                ('response', models.TextField(null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='official_app.station')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('applicant_name', models.TextField()),
                ('applicant_uid', models.TextField()),
                ('applicant_gender', models.TextField()),
                ('applicant_address', models.TextField(null=True)),
                ('complain', models.TextField()),
                ('response', models.TextField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='official_app.station')),
            ],
        ),
    ]
