# Generated by Django 3.1.4 on 2021-05-15 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complain',
            new_name='complaint',
        ),
    ]
