# Generated by Django 3.1.4 on 2021-05-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('official_app', '0053_auto_20210515_1811'),
        ('user_app', '0002_auto_20210515_1806'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='Request',
        ),
    ]
