# Generated by Django 3.1.4 on 2021-05-15 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_auto_20210321_0734'),
        ('user_app', '0003_auto_20210515_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='applicant_address',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='applicant_gender',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='applicant_name',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='applicant_uid',
        ),
        migrations.RemoveField(
            model_name='request',
            name='applicant_address',
        ),
        migrations.RemoveField(
            model_name='request',
            name='applicant_gender',
        ),
        migrations.RemoveField(
            model_name='request',
            name='applicant_name',
        ),
        migrations.RemoveField(
            model_name='request',
            name='applicant_uid',
        ),
        migrations.AddField(
            model_name='complaint',
            name='applicant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_auth.user'),
        ),
        migrations.AddField(
            model_name='request',
            name='applicant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_auth.user'),
        ),
    ]
